### ISSUE TITLE
Пожелание - Обновить сведения о Цурко - текущий текст имхо перегружен.

### ISSUE THREAD

**Issue by Ratgor** [VibroBox/vibrobox.landing#1]
Александр окончил Белорусский государственный университет информатики и радиоэлектроники в 2012 году по специальности «Радиоинформатика» факультета радиотехники и электроники, а также имеет академическую степень магистра технических наук и диплом исследователя. 

Более 5 лет опыта разработки встраиваемых цифровых систем и средств цифровой обработки сигналов, в том числе проекты с применением FPGA, технологий спутниковой связи, кибернетики и машинного обучения. В настоящее время ведет активную деятельность в сфере образования и науки как сотрудник научно-исследовательской части БГУИР и ассистент кафедры информационных радиотехнологий. Свободное время посвящено отдыху на природе и размышлениям.

В проекте VibroBox Александр занимается разработкой экспертной системы вибродиагностики. Ведет исследования по визуализации и автоматическому анализу данных на основе ЦОС, data science и стека технологий искусственного интеллекта. Также участвует в разработке оборудования для съёма вибрационных сигналов и данных телеметрии.

Тема магистерской диссертации: «Адаптивные алгоритмы технической диагностики подшипников качения по вибрационным сигналам на ранних стадиях зарождения дефектов».

**Comment by biodranik** [comment]
Вот по этой ссылке можно отредактировать нужный текст и сделать pull-request на изменение https://github.com/VibroBox/www.vibrobox.ru/edit/master/translations/team.json

**Comment by biodranik** [comment]
Done.
